version: '3'

services:
  ci:
    build:
      context: .
      dockerfile: ci.Dockerfile
    environment:
      - "ConnectionStrings:DefaultConnection=Server=test-db;Database=contosouniversity-test;User Id=sa;Password=yourStrong(!)Password"
    depends_on:
      - test-db
  test-db:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "6433:1433"