version: '3'

services:
  contosouniversity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=db;Database=contosouniversity;User Id=sa;Password=yourStrong(!)Password"
    ports:
      - "8080:80"
  db:
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5433:1433"